server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기의 합을 100MB 제한


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ENC(THELZDUlQMfAK7O8pv470NvjBfTiuHNpZwjDVd3uLUgCOIsUdFr5m2Y1Zdz4M/pI)
    secret: ENC(xIo+bbs3Ba0oiFAxLRXPzVJpxIEW/ma1ozwYY0zMQ3+MYOiq//LD5V3GANqw8TDp)

token:
  secret: ENC(Wp8halbp3gsww9PTZXSz10v22KvlYje8BIj0nCq30N68wJyCYogAZA==) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m) #900000
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60(s) x 60(m) x 24(h) x 14(d) #1209600000

jasypt:
  password: ${PASSWORD}